package model;

public enum Category {
    TSHIRTS, SWEATERS, HOODIES, JEANS, DRESSES, SKIRTS,
    JACKETS, COATS, BLOUSES, SHORTS, SHOES, BOOTS,
    SNEAKERS, SANDALS, HEELS, BAGS, HATS, SCARVES,
    BELTS, JEWELRY, KIDS_CLOTHING, KIDS_SHOES
}